### ISSUE TITLE
wyklad

### ISSUE THREAD

**Issue by swiersoon** [rmhere/lecture-comp-arch-org#1]
mowil Pan, zeby pisac, jak mozna wzbogadzic i "ulepszyc" wyklad, wiec pisze swoja sugestie. A mianowicie tozsamosci boolowskie byly w poprzednim semestrze, mozna je umiescic w wykladzie dla przypomnienia, ale nie poswiecalbym im zbytniej uwagi. Ta sama sytuacja z bramkami logicznymi. Natomiast skonczyl Pan wyklad na przerzutniku, dokladnie JK. Jesli na kolejnym wykladzie bedzie szczegolowo opowiedziane jak owe przerzutniki dzialaja to wszystko w porzadku. jesli natomiast to wszystko o przerzutnikach, to pragne przypomniec, iz przerzutniki beda na laboratoriach i szybkie wytlumaczenie na podstawie tablicy wejsc, wyjsc i stanu ukladu niestety nie wystarczy. Przynajmniej dla mnie. Pozdrawiam

**Comment by rmhere** [comment]
Dziękuję za sugestię. Ten dodatkowy wykład związany z częścią laboratoryjną opracowany był po raz pierwszy na bazie uwag zeszłorocznych studentów. W przyszłej edycji kursu dodam także szersze omówienie zasady działania układów (w tej już się nie uda), ale pozostawię części związane z tożsamościami i minimalizacją, ponieważ tego też dotyczyły uwagi studentów. Wygląda więc na to, że ten jeden wykład w przyszłym roku zostanie rozszerzony do dwóch.
